#!/bin/bash
set -o nounset -o errexit -o pipefail

cd /tmp && \
  wget https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.4.906-amd64.deb && \
  gdebi -n rstudio-server-1.4.906-amd64.deb && \
  rm rstudio-server-1.4.906-amd64.deb
